---
# tasks file for nginx-pi

- block:
    - name: install nginx
      apt: package={{ item }} state=present
      with_items:
        - nginx
    - name: start nginx
      service: 
        name: "{{ item }}"
        state: started
        enabled: yes
      with_items:
        - "nginx"
    - name: symlink motion lastsnap into web docroot
      file:
        src:  "{{ motion_lastsnap_image }}"
        dest: /var/www/html/image.jpg
        state: link
  when:
    - ansible_os_family == "Debian"
    - nginx_should_run is defined and (nginx_should_run|bool)
  become: true
  tags:
    - nginx-pi
