---
- name: install packages for all systems
  apt: package={{ item }} state=present
  with_items:
    - vim
    - bc
    - lsof
    - python-pip
    - python3-pip
  become: true
  tags:
    - vim
    - bc
    - lsof
    - common-packages

