---
- name: install packages for all systems
  apt: 
    name:
      - vim
      - bc
      - lsof
      - python3-pip
      - rsyslog
      - htop
      - lm_sensors
    state: present
  become: true
  tags:
    - vim
    - bc
    - lsof
    - common-packages
    - rsyslog
    - htop
    - lm_sensors

