---
- name: install packages for all systems
  apt: 
    name:
      - vim
      - bc
      - lsof
      - python3-pip
    state: present
  become: true
  tags:
    - vim
    - bc
    - lsof
    - common-packages

