---
# tasks file for grafana

- block:

  - name: download grafana package from their releases dir
    get_url:
      url: "https://s3-us-west-2.amazonaws.com/grafana-releases/release/grafana_{{ grafana_version }}_{{ grafana_arch }}.deb"
      dest: "/var/tmp/grafana_{{ grafana_version }}_{{ grafana_arch }}.deb"

  - name: install grafana package
    apt:
      deb: "/var/tmp/grafana_{{ grafana_version }}_{{ grafana_arch }}.deb"
      state: present

  - name: start grafana service
    service: name=grafana-server state=started enabled=yes

  # note - this must line up with the role/influxdb list of databases
  - name: Create influxdb datasources
    grafana_datasource:
      name: "{{ item }}"
      grafana_url: "{{ grafana_url }}"
      grafana_user: "{{ grafana_user }}"
      grafana_password: "{{ grafana_password }}"
      ds_type: influxdb
      url: http://influxdb:8086
      database: "{{ item }}"
      state: present
    with_items:
      - testdb
      - pihole
      - weatherflow

  become: true
  tags:
    - grafana

