---

- name: common config
  hosts: all
  gather_facts: true
  remote_user: "{{ remote_user }}"      # in group_vars or host_vars
  roles:
    - apt-cache
    - hostname
    - ntp
    - common
    - mosquitto-clients

- name: all raspi
  hosts: raspi
  gather_facts: false
  remote_user: "{{ remote_user }}" 
  roles:
    - telegraf
    - pi-stats

- name: pi3jr only
  hosts: pi3jr
  gather_facts: false
  remote_user: "{{ remote_user }}" 
  roles:
    - mosquitto
    - influxdb
    - grafana

- name: pi3 only
  hosts: pi3
  gather_facts: false
  remote_user: "{{ remote_user }}" 
  roles:
    - iptables-persistent
