---

- name: common config
  hosts: all
  gather_facts: true
  remote_user: "{{ remote_user }}"      # in group_vars or host_vars
  roles:
    - firstboot
    - apt-cache
    - hostname
    - ntp
    - timezone
    - common-packages
    - mosquitto-clients
    - crontab
    - vimrc

- name: all raspi
  hosts: raspi
  gather_facts: false
  remote_user: "{{ remote_user }}" 
  roles:
    - pi-pass
    - apt-upgrade
    - apt-autoremove
    - pi-stats
    - netmon
    - localization
    ####- telegraf

- name: all ubuntu nuc
  hosts: nucs
  gather_facts: false
  remote_user: "{{ remote_user }}" 
  roles:
    - apt-upgrade
    - localization

- name: pi3 only
  hosts: pi3
  gather_facts: false
  remote_user: "{{ remote_user }}" 
  roles:
    - iptables-persistent

- name: pi only
  hosts: pi
  gather_facts: false
  remote_user: "{{ remote_user }}" 
  roles:
    - nginx-pi

# - name: pi4 only
#   hosts: pi4
#   gather_facts: false
#   remote_user: "{{ remote_user }}"
#   roles:
#     - mosquitto
#     - weewx
