set ts=4
set expandtab
syntax on
set background=dark

autocmd filetype css        setlocal expandtab tabstop=2 shiftwidth=2 softtabstop=2
autocmd filetype go         setlocal expandtab tabstop=2 shiftwidth=2 softtabstop=2
autocmd filetype html       setlocal expandtab tabstop=2 shiftwidth=2 softtabstop=2
autocmd filetype python     setlocal expandtab tabstop=4 shiftwidth=4 softtabstop=4
autocmd filetype sh         setlocal expandtab tabstop=2 shiftwidth=2 softtabstop=2
autocmd filetype tf         setlocal expandtab tabstop=2 shiftwidth=2 softtabstop=2
autocmd filetype typescript setlocal expandtab tabstop=2 shiftwidth=2 softtabstop=2
autocmd filetype vim        setlocal expandtab tabstop=2 shiftwidth=2 softtabstop=2
autocmd filetype yaml       setlocal expandtab tabstop=4 shiftwidth=4 softtabstop=4
