---
# tasks file for iptables-persistent

- name: install iptables-persistent
  environment:
    DEBIAN_FRONTEND: NONINTERACTIVE
  apt: package={{ item }} state=present
  with_items:
    - iptables-persistent
  become: true
  tags: iptables-persistent

- name: block camera DNS lookups
  iptables:
    chain: INPUT
    source: 192.168.1.47
    jump: DROP
    comment: "block amcrest camera"
  become: true
  tags: iptables-persistent
  notify: iptables-save
