---
# tasks file for iptables-persistent

- block:

  - name: install iptables-persistent
    environment:
      DEBIAN_FRONTEND: NONINTERACTIVE
    apt: package={{ item }} state=present
    with_items:
      - iptables-persistent

  - name: block camera DNS lookups
    iptables:
      chain: INPUT
      source: 192.168.1.47
      protocol: udp
      destination_port: "53"
      jump: DROP
      comment: "block amcrest camera"
    notify: iptables-save

  become: true
  tags: iptables-persistent
