---
# tasks file for weewx

- block:

  - name: weewx apt key
    apt_key:
      url: http://weewx.com/keys.html
      state: present

  - name: weewx apt repo location
    apt_repository:
      repo: deb [arch=all] http://weewx.com/apt/python3 buster main
      state: present

  - name: install weewx and coreqs
    package: 
      name:
        - weewx
        - sqlite3
        - nginx
        - git
        - python3-paho-mqtt
      state: "present"
      update_cache: yes

  - name: grab Belchertown skin
    git:
      repo: 'https://github.com/poblabs/weewx-belchertown.git'
      dest: /var/tmp/weewx-belchertown
    register: belchertown_cloned

  - name: install Belchertown skin
    command:
      cmd: wee_extension --install /var/tmp/weewx-belchertown
      creates: /etc/weewx/skins/Belchertown

  - name: grab MQTT extension
    git:
      repo: 'https://github.com/matthewwall/weewx-mqtt.git'
      dest: /var/tmp/weewx-mqtt
    register: mqtt_extension_grabbed

  - name: install MQTT extension
    command:
      cmd: wee_extension --install /var/tmp/weewx-mqtt
      creates: /usr/share/weewx/user/mqtt.py

  - name: enable MQTT extension (to pi4)
    lineinfile:
      path: /etc/weewx/weewx.conf
      regexp: 'server_url = INSERT_SERVER_URL_HERE'
      line:   '        server_url = mqtt://192.168.1.164:1883'
    register: mqtt_extension_enabled
    notify: restart weewx

  - name: enable weewx debug
    lineinfile:
      path: /etc/weewx/weewx.conf
      regexp: 'debug = 0'
      line:   'debug = 1'
    notify: restart weewx

  #- name: install weewx config files
    #copy:
      #src:  "{{ item }}"
      ##dest: "/etc/weewx/{{ item }}"
    #with_items:
      #- weewx.conf
    #notify: restart weewx

  become: true
  tags: weewx

#--- to do - the MQTT section should look like
#[StdRESTful]
#    [[MQTT]]
#        server_url = mqtt://pi4:1883
#        topic = weather
#        binding = archive, loop
#        aggregation = aggregate
#        log_success = false
#
#--- to do - the Belchertown section should look like
#
#    [[Belchertown]]
#        skin = Belchertown
#        HTML_ROOT = /var/www/html/weewx/belchertown
#
#        [[[Extras]]]
#        mqtt_websockets_enabled = 1
#        mqtt_websockets_host = 192.168.1.164
#        mqtt_websockets_port = 9001
#        mqtt_websockets_ssl = 0
#        mqtt_websockets_topic = "weather/loop"
#

