---

- block:
    - name: update apt cache
      apt: update_cache=yes cache_valid_time={{ apt_cache_valid_time }}
      register: apt_cache_updated
  when:
    - ansible_os_family == "Debian"
    - update_apt_cache is defined and (update_apt_cache|bool)
  become: true
  tags:
    - apt-cache
