---
# tasks file for firstboot

- block:

  - name: set role-specific variables if this is the first boot
    set_fact:
      set_pi_pass: True
      update_apt_cache: True
      run_apt_upgrade:   True
   
  - name: Display all variables/facts known for a host
    debug:
      var: hostvars[inventory_hostname]
      verbosity: 1

  when:
    - firstboot is defined and (firstboot|bool)
    - ansible_os_family == "Debian"
    - ansible_lsb.id is defined and (ansible_lsb.id == "Raspbian" or ansible_lsb.id == "Debian")
  become: true
  tags:
    - firstboot
    
