---
# tasks file for apt-upgrade

- block:
    - name: run apt-upgrade
      apt: upgrade=yes
  when:
    - ansible_os_family == "Debian"
    - run_apt_upgrade is defined and (run_apt_upgrade|bool)
  become: true
  tags: apt-upgrade
