---
# tasks file for pi-pass

- block:

  - name: pi user password
    user:
      name: pi
      password: "{{ PI_PASSWORD }}"

  - name: pi user authorized keys
    authorized_key:
      user: pi
      key: "{{ item }}"
    with_file:
      - id_rsa_nopass.pub

  become: true
  when:
    - ansible_os_family == "Debian"
    - set_pi_pass is defined and (set_pi_pass|bool)
  tags:
    - pi-pass
