---
# tasks file for mosquitto

- block:
  - name: install mosquitto package
    package: 
      name:  "mosquitto"
      state: "present"

  - name: install mosquitto config files
    copy:
      src:  "{{ item }}"
      dest: "/etc/mosquitto/conf.d/{{ item }}"
    with_items:
      - anon-listener.conf
      - bridge-to-lightsail.conf
      - websockets-listener.conf
    notify: restart mosquitto

  become: true
  tags: mosquitto
