---
# tasks file for mosquitto

- block:
  - name: install mosquitto package
    package: 
      name:  "mosquitto"
      state: "present"

  - name: install mosquitto config files
    copy:
      src:  "{{ item }}"
      dest: "/etc/mosquitto/conf.d/{{ item }}"
    with_items:
      - 1883.conf
      - 9001.conf
    notify: restart mosquitto

  become: true
  tags: mosquitto
