---
# tasks file for telegraf

- name: download telegraf package from their releases dir (check the cert)
  get_url:
    url: "https://dl.influxdata.com/telegraf/releases/telegraf_{{ telegraf_version }}_{{ telegraf_arch }}.deb"
    dest: "/var/tmp/telegraf_{{ telegraf_version }}_{{ telegraf_arch }}.deb"
  become: true
  tags: telegraf

- name: install telegraf package 
  apt:
    deb: "/var/tmp/telegraf_{{ telegraf_version }}_{{ telegraf_arch  }}.deb"
    state: present
  become: true
  tags: telegraf

- name: example copying file with owner and permissions
  copy:
    src: telegraf.conf
    dest: /etc/telegraf/telegraf.conf
  become: true
  tags: telegraf
  notify: restart telegraf

- name: start telegraf service
  service: name=telegraf state={{ telegraf_state }} enabled={{ telegraf_enabled }}
  become: true
  tags: telegraf

# - name: stop/disable telegraf service
#   service: name=telegraf state=stopped enabled=no
#   become: true
#   tags: telegraf
